[service]
port = 9000         # 路由监听的端口
log_level = "trace" # trace | debug | *info | warn | error | off

[service.default]
retry = 2
cooldown = "3min"

[backend]
sglang-qwen3.5-35B-A3B = "http://172.17.250.163:30001"
sglang-qwen3.5-122B-A10B = "http://172.17.250.163:30000"

[backend.aliyun]
base-url = "https://dashscope.aliyuncs.com/apps/anthropic"
api-key = "sk-"
retry = 5
cooldown = "30s"

[router]
Qwen3.5-35B-A3B = ["sglang-qwen3.5-35B-A3B", "aliyun"]
Qwen3.5-122B-A10B = ["sglang-qwen3.5-122B-A10B", "aliyun"]
